version: '3'
services:
    db:
        image: mariadb:10
        command: --default-authentication-plugin=mysql_native_password
        container_name: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: '12345678'
            MYSQL_DATABASE: 'ecommerce'
        ports:
            - "3306:3306"
        volumes:
            - './db/mysql:/var/lib/mysql'
            - './docker/db:/docker-entrypoint-initdb.d'
    ecommerce:
        build: .
        restart: always
        container_name: ecommerce
        volumes:
            - '.:/var/www/html'
            - './docker/config/php.ini:/usr/local/etc/php/php.ini'
            - './docker/config/apache2.conf:/etc/apache2/apache2.conf'
            - './docker/config/000-default.conf:/etc/apache2/sites-available/000-default.conf'
            - './docker/config/ports.conf:/etc/apache2/ports.conf'
        depends_on:
            - db
        ports:
            - "80:80"
        environment:
            APP_URL: ${APP_URL}
            DB_DRIVER: ${DB_DRIVER}
            DB_NAME: ${DB_NAME}
            DB_HOST: ${DB_HOST}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_USER: ${DB_USER}
    adminer:
        image: adminer
        container_name: adminer
        restart: always
        depends_on:
            - db
        ports:
            - "8080:8080"
networks:
    default: